stages :
  - build
  - test
  - release

before_script:
   - sudo apt-get update -y
   - sudo apt-get install -y cmake

build-project:
  stage : build
  tags: ubuntu
  script:
    - mkdir Step7_build
    - cd Step7_build
    - cmake ../Step7 && cmake --build . && make

test-project:
  stage: test
  tags: ubuntu
  script:
    - mkdir Step7_build
    - cd Step7_build
    - cmake ../Step7 && cmake --build . && make
    - ctest -VV

release-project:
  stage: release
  tags: ubuntu
  script:
    - mkdir Step7_build
    - cd Step7_build
    - cmake ../Step7 && cmake --build . && make
    - cpack -G DEB
  artifacts:
    paths:
      - ./Step7_build/Tutorial-*-Linux.deb

